DROP TABLE IF EXISTS Alcoholic CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS Drink CASCADE;
DROP TABLE IF EXISTS Ingredient_Drink CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
